# Generated by Django 5.0.6 on 2024-06-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useraddress",
            table="user_address",
        ),
    ]
