# Generated by Django 5.0.6 on 2024-06-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_useraddress_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useraddress",
            table=None,
        ),
    ]
